package com.example.odata.service;

import com.example.odata.model.Product;
import org.apache.olingo.commons.api.data.Entity;
import org.apache.olingo.commons.api.data.EntityCollection;
import org.apache.olingo.commons.api.data.Property;
import org.apache.olingo.commons.api.data.ValueType;
import org.apache.olingo.commons.api.edm.EdmEntitySet;
import org.apache.olingo.commons.api.edm.EdmEntityType;
import org.apache.olingo.commons.api.format.ContentType;
import org.apache.olingo.commons.api.http.HttpHeader;
import org.apache.olingo.commons.api.http.HttpStatusCode;
import org.apache.olingo.server.api.OData;
import org.apache.olingo.server.api.ODataApplicationException;
import org.apache.olingo.server.api.ODataRequest;
import org.apache.olingo.server.api.ODataResponse;
import org.apache.olingo.server.api.ServiceMetadata;
import org.apache.olingo.server.api.processor.EntityCollectionProcessor;
import org.apache.olingo.server.api.serializer.EntityCollectionSerializerOptions;
import org.apache.olingo.server.api.serializer.ODataSerializer;
import org.apache.olingo.server.api.serializer.SerializerException;
import org.apache.olingo.server.api.serializer.SerializerResult;
import org.apache.olingo.server.api.uri.UriInfo;
import org.apache.olingo.server.api.uri.UriResource;
import org.apache.olingo.server.api.uri.UriResourceEntitySet;
import org.apache.olingo.server.api.uri.queryoption.FilterOption;
import org.apache.olingo.server.api.uri.queryoption.ExpandOption;
import org.apache.olingo.server.api.uri.queryoption.ExpandItem;
import org.apache.olingo.server.api.uri.queryoption.SelectOption;
import org.apache.olingo.server.api.uri.queryoption.expression.Expression;
import org.apache.olingo.server.api.uri.queryoption.expression.ExpressionVisitException;

import com.example.odata.model.Brand; // Import Brand
import org.apache.olingo.commons.api.data.Link; // Import Link

import java.util.Iterator;
import java.util.List;
import java.util.Locale;

public class DemoEntityCollectionProcessor implements EntityCollectionProcessor {

    private OData odata;
    private ServiceMetadata serviceMetadata;
    private Storage storage;
    private BrandStorage brandStorage;

    public DemoEntityCollectionProcessor(Storage storage, BrandStorage brandStorage) {
        this.storage = storage;
        this.brandStorage = brandStorage;
    }

    @Override
    public void init(OData odata, ServiceMetadata serviceMetadata) {
        this.odata = odata;
        this.serviceMetadata = serviceMetadata;
    }

    @Override
    public void readEntityCollection(ODataRequest request, ODataResponse response, UriInfo uriInfo,
            ContentType responseFormat) throws ODataApplicationException, SerializerException {

        // 1st retrieve the requested EntitySet from the uriInfo
        List<UriResource> resourcePaths = uriInfo.getUriResourceParts();
        UriResourceEntitySet uriResourceEntitySet = (UriResourceEntitySet) resourcePaths.get(0);
        EdmEntitySet edmEntitySet = uriResourceEntitySet.getEntitySet();

        // 2nd: fetch the data from backend
        // In a real app, you would pass the filter options to the database query
        EntityCollection entityCollection = getData(edmEntitySet);

        // 3rd: apply System Query Options provided by OData ($filter)
        FilterOption filterOption = uriInfo.getFilterOption();
        if (filterOption != null) {
            // Apply $filter
            try {
                // Determine the key for the loop
                List<Entity> entityList = entityCollection.getEntities();
                Iterator<Entity> entityIterator = entityList.iterator();

                while (entityIterator.hasNext()) {
                    // Iterate and remove elements that don't match the filter
                    Entity currentEntity = entityIterator.next();
                    Expression filterExpression = filterOption.getExpression();

                    // Convert Olingo Entity back to Product to use our Visitor (or make Visitor use
                    // Entity)
                    // It is easier to make Visitor use Entity directly for generic support,
                    // BUT for this specific example I created a ProductVisitor.
                    // Let's create a temporary Product from the Entity to reuse the Visitor logic.
                    Integer id = (Integer) currentEntity.getProperty("ID").getValue();
                    String name = (String) currentEntity.getProperty("Name").getValue();
                    String desc = (String) currentEntity.getProperty("Description").getValue();
                    Double price = (Double) currentEntity.getProperty("Price").getValue();
                    // brandId might not be in the entity properties generated by getData initial
                    // pass if we didn't add it
                    // But we will fix getData below. For filter visitor we just need a dummy
                    // brandId or the real one if available
                    // Let's assume 0 for now as filter visitor doesn't use brandId yet.
                    Product prod = new Product(id, name, desc, price, 0);

                    ProductFilterExpressionVisitor expressionVisitor = new ProductFilterExpressionVisitor(prod);
                    Object visitorResult = filterExpression.accept(expressionVisitor);

                    // The result of the filter expression must be of type Boolean
                    if (visitorResult instanceof Boolean) {
                        if (!Boolean.TRUE.equals(visitorResult)) {
                            // The expression evaluated to false (or null), so we remove the entity
                            entityIterator.remove();
                        }
                    } else {
                        throw new ODataApplicationException("A filter expression must evaluate to type Boolean",
                                HttpStatusCode.BAD_REQUEST.getStatusCode(), Locale.ENGLISH);
                    }
                }

            } catch (ExpressionVisitException e) {
                throw new ODataApplicationException("Exception in filter evaluation",
                        HttpStatusCode.INTERNAL_SERVER_ERROR.getStatusCode(), Locale.ENGLISH);
            }
        }

        // 4th: Handle $expand
        ExpandOption expandOption = uriInfo.getExpandOption();
        if (expandOption != null) {
            // Retrieve the user defined expand items
            List<ExpandItem> expandItems = expandOption.getExpandItems();
            for (ExpandItem expandItem : expandItems) {
                // We only have one navigation property "Brand"
                if (expandItem.getResourcePath().getUriResourceParts().get(0).toString().equals("Brand")) {
                    // Logic to fetch related data
                    // Iterate over the already fetched products
                    List<Entity> entityList = entityCollection.getEntities();
                    for (Entity entity : entityList) {
                        // Get the BrandID from the entity (we must ensure it is added in getData)
                        Property brandIdProp = entity.getProperty("BrandID");
                        if (brandIdProp != null) {
                            Integer brandID = (Integer) brandIdProp.getValue();

                            // Call Microservice to get Brand
                            Brand brand = brandStorage.getBrandById(brandID);

                            if (brand != null) {
                                // Create Brand Entity
                                Entity brandEntity = new Entity();
                                brandEntity.addProperty(new Property(null, "ID", ValueType.PRIMITIVE, brand.getId()));
                                brandEntity
                                        .addProperty(new Property(null, "Name", ValueType.PRIMITIVE, brand.getName()));
                                brandEntity.addProperty(
                                        new Property(null, "Country", ValueType.PRIMITIVE, brand.getCountry()));
                                brandEntity.setId(createId(DemoEdmProvider.ES_BRANDS_NAME, brand.getId()));

                                // Create Link
                                Link link = new Link();
                                link.setTitle("Brand");
                                link.setInlineEntity(brandEntity);

                                // Add link to Product Entity
                                entity.getNavigationLinks().add(link);
                            }
                        }
                    }
                }
            }
        }

        // 5th: Handle $select
        SelectOption selectOption = uriInfo.getSelectOption();

        // 6th: create a serializer based on the requested format (json)
        ODataSerializer serializer = odata.createSerializer(responseFormat);

        // 7th: configure the serializer with context and options ($select, $expand)
        EdmEntityType edmEntityType = edmEntitySet.getEntityType();
        String selectList = odata.createUriHelper().buildContextURLSelectList(edmEntityType, expandOption,
                selectOption);
        org.apache.olingo.commons.api.data.ContextURL contextUrl = org.apache.olingo.commons.api.data.ContextURL.with()
                .entitySet(edmEntitySet)
                .selectList(selectList)
                .build();

        final String id = request.getRawBaseUri() + "/" + edmEntitySet.getName();
        EntityCollectionSerializerOptions opts = EntityCollectionSerializerOptions.with()
                .id(id)
                .contextURL(contextUrl)
                .select(selectOption)
                .expand(expandOption)
                .build();

        // 8th: serialize
        SerializerResult serializerResult = serializer.entityCollection(serviceMetadata, edmEntityType,
                entityCollection, opts);

        // 9th: configure the response object
        response.setContent(serializerResult.getContent());
        response.setStatusCode(HttpStatusCode.OK.getStatusCode());
        response.setHeader(HttpHeader.CONTENT_TYPE, responseFormat.toContentTypeString());
    }

    private EntityCollection getData(EdmEntitySet edmEntitySet) {
        EntityCollection productsCollection = new EntityCollection();
        // Check which set is requested
        if (DemoEdmProvider.ES_PRODUCTS_NAME.equals(edmEntitySet.getName())) {
            List<Entity> entityList = productsCollection.getEntities();

            // map from POJO to Olingo Entity
            for (Product product : storage.getProducts()) {
                Entity e = new Entity()
                        .addProperty(new Property(null, "ID", ValueType.PRIMITIVE, product.getId()))
                        .addProperty(new Property(null, "Name", ValueType.PRIMITIVE, product.getName()))
                        .addProperty(new Property(null, "Description", ValueType.PRIMITIVE, product.getDescription()))
                        .addProperty(new Property(null, "Price", ValueType.PRIMITIVE, product.getPrice()))
                        .addProperty(new Property(null, "BrandID", ValueType.PRIMITIVE, product.getBrandId()));
                e.setId(createId(edmEntitySet.getName(), product.getId()));
                entityList.add(e);
            }
        } else if (DemoEdmProvider.ES_BRANDS_NAME.equals(edmEntitySet.getName())) {
            List<Entity> entityList = productsCollection.getEntities();
            for (Brand brand : brandStorage.getBrands()) {
                Entity e = new Entity()
                        .addProperty(new Property(null, "ID", ValueType.PRIMITIVE, brand.getId()))
                        .addProperty(new Property(null, "Name", ValueType.PRIMITIVE, brand.getName()))
                        .addProperty(new Property(null, "Country", ValueType.PRIMITIVE, brand.getCountry()));
                e.setId(createId(edmEntitySet.getName(), brand.getId()));
                entityList.add(e);
            }
        }
        return productsCollection;
    }

    private java.net.URI createId(String entitySetName, Object id) {
        try {
            return new java.net.URI(entitySetName + "(" + String.valueOf(id) + ")");
        } catch (Exception e) {
            throw new RuntimeException("Unable to create id for entity: " + entitySetName, e);
        }
    }
}
